"""
create_test_workbooks.py
=========================
Generates three sample .xlsx workbooks used across Phase 1 testing:
  - pricing.xlsx    (arithmetic, IF, VLOOKUP)
  - payroll.xlsx     (SUMIF/SUMIFS, nested IF)
  - inventory.xlsx  (COUNTIF, MIN/MAX, and a deliberate circular
                     reference + a deliberate type error for testing
                     error handling)

NOTE (documented for the viva): because these files are generated by
openpyxl rather than opened/saved by Excel, they have NO Excel-cached
formula values. tests/expected_values.py hand-computes the correct
result for every formula cell instead, and that is what
test_pipeline.py checks the evaluator against -- this is Phase 1's
correctness baseline, standing in for "Excel's own computed values"
until the workbooks are opened once in real Excel/LibreOffice.
"""

import os
import openpyxl

OUT_DIR = os.path.join(os.path.dirname(__file__), "workbooks")


def build_pricing():
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Sheet1"
    # Unit price, quantity, discount threshold
    ws["A1"], ws["B1"], ws["C1"] = "UnitPrice", "Qty", "Total"
    ws["A2"], ws["B2"] = 10, 5
    ws["A3"], ws["B3"] = 20, 12
    ws["A4"], ws["B4"] = 7.5, 3
    ws["C2"] = "=A2*B2"
    ws["C3"] = "=A3*B3"
    ws["C4"] = "=A4*B4"
    ws["C5"] = "=SUM(C2:C4)"
    # Discount: if quantity > 10, apply 10% off
    ws["D2"] = "=IF(B2>10,C2*0.9,C2)"
    ws["D3"] = "=IF(B3>10,C3*0.9,C3)"
    ws["D4"] = "=IF(B4>10,C4*0.9,C4)"
    wb.save(os.path.join(OUT_DIR, "pricing.xlsx"))


def build_payroll():
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Sheet1"
    ws["A1"], ws["B1"], ws["C1"] = "Employee", "Dept", "Salary"
    ws["A2"], ws["B2"], ws["C2"] = "Alice", "Eng", 5000
    ws["A3"], ws["B3"], ws["C3"] = "Bob", "Sales", 4000
    ws["A4"], ws["B4"], ws["C4"] = "Carol", "Eng", 5500
    ws["A5"], ws["B5"], ws["C5"] = "Dave", "Sales", 4200
    # Total salary for Eng department
    ws["E1"] = "=SUMIF(B2:B5,\"Eng\",C2:C5)"
    # Bonus: 10% if salary > 4500, else 5%
    ws["D2"] = "=IF(C2>4500,C2*1.1,C2*1.05)"
    ws["D3"] = "=IF(C3>4500,C3*1.1,C3*1.05)"
    ws["D4"] = "=IF(C4>4500,C4*1.1,C4*1.05)"
    ws["D5"] = "=IF(C5>4500,C5*1.1,C5*1.05)"
    wb.save(os.path.join(OUT_DIR, "payroll.xlsx"))


def build_inventory():
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Sheet1"
    ws["A1"], ws["B1"] = "Item", "Stock"
    ws["A2"], ws["B2"] = "Widget", 3
    ws["A3"], ws["B3"] = "Gadget", 15
    ws["A4"], ws["B4"] = "Gizmo", 0
    ws["C1"] = "=COUNTIF(B2:B4,0)"          # count of out-of-stock items
    ws["C2"] = "=MIN(B2:B4)"
    ws["C3"] = "=MAX(B2:B4)"

    # Deliberate circular reference for testing dependency_graph.py's
    # cycle detection: D1 depends on D2, D2 depends on D1.
    ws["D1"] = "=D2+1"
    ws["D2"] = "=D1+1"

    # Deliberate type error for testing evaluator's semantic error path:
    # summing a text cell should raise a SemanticError.
    ws["E1"] = "Not A Number"
    ws["E2"] = "=SUM(E1)"

    wb.save(os.path.join(OUT_DIR, "inventory.xlsx"))


if __name__ == "__main__":
    os.makedirs(OUT_DIR, exist_ok=True)
    build_pricing()
    build_payroll()
    build_inventory()
    print(f"Test workbooks written to {OUT_DIR}")
