"""
expected_values.py
===================
Hand-computed "ground truth" for every formula cell in pricing.xlsx and
payroll.xlsx (worked out manually from the raw data, the same way a
human would check Excel's own output). This is what test_pipeline.py
compares the evaluator's output against.

Why not just use openpyxl's cached values? Because our test workbooks
are generated by openpyxl itself (see create_test_workbooks.py), and
openpyxl does not evaluate formulas -- it never writes cached values.
In a real deployment (workbooks that came from an analyst's actual
Excel file) the extractor's cached_value field would be populated and
could be used instead; that comparison path already exists in
extractor.py's ExtractedCell.cached_value for exactly that case.
"""

PRICING_EXPECTED = {
    ("Sheet1", "C2"): 50,
    ("Sheet1", "C3"): 240,
    ("Sheet1", "C4"): 22.5,
    ("Sheet1", "C5"): 312.5,
    ("Sheet1", "D2"): 50,        # B2=5, not >10 -> no discount
    ("Sheet1", "D3"): 216.0,     # B3=12 >10 -> 240*0.9
    ("Sheet1", "D4"): 22.5,      # B4=3, not >10 -> no discount
}

PAYROLL_EXPECTED = {
    ("Sheet1", "E1"): 10500,     # Eng: Alice 5000 + Carol 5500
    ("Sheet1", "D2"): 5500.0,    # 5000 > 4500 -> *1.1
    ("Sheet1", "D3"): 4200.0,    # 4000 not > 4500 -> *1.05
    ("Sheet1", "D4"): 6050.0,    # 5500 > 4500 -> *1.1
    ("Sheet1", "D5"): 4410.0,    # 4200 not > 4500 -> *1.05
}
